import React, { Component } from 'react'

class Curriculum extends Component {
  render() {
    return (
      <div>
        <div className="post-header">
          <h1 className="post-title">Curriculum</h1>
        </div>
          <div className="post-content">
            <p ><em>During the three academic terms, students take courses, listed below.</em></p>
            <p>This integrated program is composed of four terms of honors level academic courses.  All are conducted in a seminar format and include field trips. The curriculum integrates mathematics into the social science and natural science courses.  The reason for the modest place of science in the curriculum is because the entrants have followed the science stream in ninth and tenth grades.  After the academic terms, the students take a four-month, full-time internship, guided by a weekly seminar.  The Program is equivalent to eleventh and twelfth grades. <strong>A Certificate in Liberal Arts is awarded upon completion of the Program.</strong></p>
            
            <p ><strong>Academic and Creative Writing:</strong> Being able to write well in a variety of fashions is a critical 21st-century skill all young people should work to acquire. This course is designed for that purpose. Throughout this course, students will explore the six stages of the writing process (pre-writing, planning, drafting, revising, publishing) from a hands-on approach. In order to gain an understanding of effective writing, students will read and analyze multiple texts in order to learn how to critically think about and develop different forms and styles of writing. Students will complete three book reports throughout the course to develop their analytical eye. Additionally, student-led workshops will allow students to read and critique the work of their peers throughout the course. Through this process, students will learn to accept feedback and provide constructive criticism to their peers. The students will have four workshops throughout the year: one fiction essay, one argumentative essay, one profile, and one non-fiction essay. </p>
            <p ><strong>Environmental Studies:</strong> Widespread environmental problems are some of the most pressing global issues of our time. They have significant scientific, moral, and social dimensions that require thoughtful analysis from a range of perspectives. This interdisciplinary course uses the basic concepts of environmental studies to explore global, regional, and individual issues. Throughout the course, students will analyze the environment in relation to the economy, society, gender, food, history, tourism, politics, and consumption. Students will diagnose their personal relationship with the environment and develop a deep understanding of their connection to the natural world from a personal perspective as well as a global and regional perspective. Students will debate, discuss, and analyze problems and their possible solutions. They will have four main projects in this course to develop their research, writing, and presentation skills. In term 1, students will do a presentation on an ecological cycle. In term 2, they will analyze urban development by designing an environmentally friendly city. In term 3, they will dissect consumption and come up with solutions for waste reduction. In term 4, they will give a speech on an environmental issue they are passionate about, drawing from what they learned over the course of the year. <em>This course was intended to be hands-on with various field trips. Due to COVID-19, this course was administered mostly online and most field trips were, unfortunately, canceled.</em> </p>
            <p ><strong>Literature:</strong>This course was designed to not only examine and learn from well-known writers of prose, poetry and philosophy but for students to be able to learn to develop analytical skills. Delving into many genres, including fairy tales, poetry, philosophical and theological texts, philosophical novels and folk tales, the students will learn to find and describe the symbols, themes, structure and concepts contained within. The students also will learn to write poetry with careful attention to meter and rhyme, including writing in celebrated forms such as the sonnet. In groups of four, they will create books of poetry and fairy tales. This course is intended to broaden and deepen the minds of students as well as introduce them to ideas and ways of thinking from all over the world. They will always be asked to relate texts and ideas to their own lives and the world around them so that they can apply what they have learned. They will read a wide range of philosophers from Plato to Sartre, and be asked to analyze their ideas and discuss them in depth. The most essential target of the course is to open and enrichen the mind and help students to be more well equipped to handle college level courses and multicultural environments. </p>
            <p ><strong>Modern World History: </strong> An understanding of the past deepens the understanding of the present and hence is crucial for critical thinkers in the 21st century. With that objective in mind, this history course examines historical events, ideas and processes from a global perspective in order to make sense of the contemporary world. In Term I, students explore the topics, among others, of the European Enlightenment, Industrialization, Age of Empires and Colonialism with a view to analyze why some societies became more materially advanced than others. In Term II, students explore various Asian encounters with and responses to colonialism. In Term III and Term IV, students acquaint themselves with modern Burmese History to be able to situate the local in the global context as well as to be able to identify future challenges of their communities. Students learn from a variety of sources: textbooks, class discussions, primary documents, essays, articles, documentaries, maps, and guest speakers. Quizzes and narrative essays consolidate the students’ grasp of the core ideas. Periodic reflections and expository essay assignments help students develop and apply their critical thinking skills.</p>
            <p ><strong>Sociological Life Across Boundary:</strong> This course explores sociological concepts. We also learn how these sociological lenses were evolved out of historical contexts; and how time and space shaped individual sociologists’ understanding of their life in sociological world. We read key sociology texts to understand how sociological questions are constructed and how sociological tools are used when inquiring life of one’s own and life across boundary. Constructing our own questions, we analyze stories, events, and phenomena we learn in the other Pre-Collegiate Program courses. Using sociological inquiry, we discuss global and local events. Applying sociological concepts, we share our life stories and experiences as we all come from diverse ethnic and regional backgrounds in Myanmar. This course lets us gain deeper understanding of implication of sociological concepts across boundaries, such as academic disciplinary boundary, nation-state boundary, and racial/ethnic boundary.</p>
            <p ><strong>Touchstones Discussions:</strong> Small group and class discussion explore issues raised by texts that are often drawn from Western classics. How students find their voices, develop cooperative learning, and augment their critical thinking is elucidated at <a href="www.touchstones.org">www.touchstones.org</a>.</p>
            
            <p ><em>Additionally, students spend significant time on each of the&nbsp;following activities.</em></p>
            <ul>
              <li ><strong>Field Trips</strong> – Students explore Yangon and Myanmar, develop observational and analytical skills, and write field reports on our bi-weekly field trips. Trips include&nbsp;visiting a garment factory, examining ancient and modern Twante kilns, and exploring exploring mangrove forests. Additionally, we take two week-long&nbsp;trips, to study Burmese history, arhitecture, and archaeology at Bagan, and to study economics, political science, and culture in rural Shan State.</li>
              <br/>
              <li ><strong>Touchstones Discussions</strong> – Touchstones uses small group and class discussion to explore issues raised by texts from many societies. Learn more about how students find their voices, develop cooperative learning, and augment their critical thinking at <a>touchstones.org</a>.</li>
              <br/>
              <li ><strong>SAT Preparation</strong> – Students learn knowledge and skills necessary to succeed on the SAT exam and <a href="./financial-aid">earn admission and scholarships</a> to foreign universities.</li>
              <br/>
              <li ><strong>Community Service</strong> – From four to eight hours each week, students learn outside of the classroom, build connections, and create positive change in their communities. Students can volunteer at the Myanmar Education Center for the Blind, teach at local monasteries, and translate Khan Academy videos into Burmese, among other activities.</li>
              <br/>
              <li ><strong>Internships</strong> – Our students gain experience and make connections in Myanmar’s professional world during a four-month <a href="./intern">internship</a>. Projects vary based on the individual’s interest and include working at the Myanmar Times, assisting research at MMRD (Myanmar Marketing Research &amp; Development), surveying workers with the International Labor Organization, and learning documentary filmmaking with Tagu Films.</li>
            </ul>
          </div>
      </div>
    )
  }
}

export default Curriculum

